// Auto-generated by: npx supabase gen types typescript --local > types/supabase.ts
// Run this command after applying migrations to keep in sync.
// Reflects: supabase/migrations/20260706120001_workspaces.sql .. 20260706120005_workspace_invites.sql

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: 'free' | 'pro';
          owner_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          plan_status: 'active' | 'canceled' | 'trialing' | 'past_due' | null;
          cancel_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          plan?: 'free' | 'pro';
          owner_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan_status?: 'active' | 'canceled' | 'trialing' | 'past_due' | null;
          cancel_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          plan?: 'free' | 'pro';
          owner_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan_status?: 'active' | 'canceled' | 'trialing' | 'past_due' | null;
          cancel_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      workspace_members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: 'admin' | 'member';
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          user_id: string;
          role?: 'admin' | 'member';
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          user_id?: string;
          role?: 'admin' | 'member';
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'workspace_members_workspace_id_fkey';
            columns: ['workspace_id'];
            isOneToOne: false;
            referencedRelation: 'workspaces';
            referencedColumns: ['id'];
          },
        ];
      };
      leads: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          company: string | null;
          role: string | null;
          status: 'new' | 'contacted' | 'qualified' | 'lost';
          assigned_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          role?: string | null;
          status?: 'new' | 'contacted' | 'qualified' | 'lost';
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          role?: string | null;
          status?: 'new' | 'contacted' | 'qualified' | 'lost';
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'leads_workspace_id_fkey';
            columns: ['workspace_id'];
            isOneToOne: false;
            referencedRelation: 'workspaces';
            referencedColumns: ['id'];
          },
        ];
      };
      deals: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          value: number;
          stage: 'new_lead' | 'contacted' | 'proposal_sent' | 'negotiation' | 'won' | 'lost';
          lead_id: string | null;
          assigned_to: string | null;
          deadline: string | null;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          value?: number;
          stage?: 'new_lead' | 'contacted' | 'proposal_sent' | 'negotiation' | 'won' | 'lost';
          lead_id?: string | null;
          assigned_to?: string | null;
          deadline?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          title?: string;
          value?: number;
          stage?: 'new_lead' | 'contacted' | 'proposal_sent' | 'negotiation' | 'won' | 'lost';
          lead_id?: string | null;
          assigned_to?: string | null;
          deadline?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'deals_workspace_id_fkey';
            columns: ['workspace_id'];
            isOneToOne: false;
            referencedRelation: 'workspaces';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'deals_lead_id_fkey';
            columns: ['lead_id'];
            isOneToOne: false;
            referencedRelation: 'leads';
            referencedColumns: ['id'];
          },
        ];
      };
      activities: {
        Row: {
          id: string;
          workspace_id: string;
          lead_id: string;
          author_id: string;
          type: 'call' | 'email' | 'meeting' | 'note';
          description: string;
          activity_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          lead_id: string;
          author_id: string;
          type: 'call' | 'email' | 'meeting' | 'note';
          description: string;
          activity_date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          lead_id?: string;
          author_id?: string;
          type?: 'call' | 'email' | 'meeting' | 'note';
          description?: string;
          activity_date?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'activities_workspace_id_fkey';
            columns: ['workspace_id'];
            isOneToOne: false;
            referencedRelation: 'workspaces';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'activities_lead_id_fkey';
            columns: ['lead_id'];
            isOneToOne: false;
            referencedRelation: 'leads';
            referencedColumns: ['id'];
          },
        ];
      };
      workspace_invites: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: 'admin' | 'member';
          token: string;
          invited_by: string;
          accepted_at: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role?: 'admin' | 'member';
          token?: string;
          invited_by: string;
          accepted_at?: string | null;
          expires_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          role?: 'admin' | 'member';
          token?: string;
          invited_by?: string;
          accepted_at?: string | null;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'workspace_invites_workspace_id_fkey';
            columns: ['workspace_id'];
            isOneToOne: false;
            referencedRelation: 'workspaces';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_workspaces: {
        Args: { p_user_id: string };
        Returns: Database['public']['Tables']['workspaces']['Row'][];
      };
      is_workspace_member: {
        Args: { p_workspace_id: string; p_user_id: string };
        Returns: boolean;
      };
      is_workspace_admin: {
        Args: { p_workspace_id: string; p_user_id: string };
        Returns: boolean;
      };
      get_workspace_members: {
        Args: { p_workspace_id: string };
        Returns: {
          user_id: string;
          role: 'admin' | 'member';
          email: string | null;
          full_name: string | null;
        }[];
      };
      count_workspace_seats: {
        Args: { p_workspace_id: string };
        Returns: number;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
