import type { Lead } from '@/types'

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    workspace_id: 'ws-1',
    name: 'Fernanda Oliveira',
    email: 'fernanda@acmecorp.com.br',
    phone: '(11) 98765-4321',
    company: 'Acme Corp',
    role: 'Diretora de Marketing',
    status: 'qualified',
    assigned_to: 'Luis Armando',
    created_at: '2026-06-01T10:00:00Z',
    updated_at: '2026-06-15T14:30:00Z',
  },
  {
    id: '2',
    workspace_id: 'ws-1',
    name: 'Ricardo Mendes',
    email: 'ricardo.mendes@techbr.com',
    phone: '(21) 99234-5678',
    company: 'TechBR Soluções',
    role: 'CEO',
    status: 'contacted',
    assigned_to: 'Ana Costa',
    created_at: '2026-06-03T09:15:00Z',
    updated_at: '2026-06-18T11:00:00Z',
  },
  {
    id: '3',
    workspace_id: 'ws-1',
    name: 'Juliana Souza',
    email: 'ju.souza@inovalabs.io',
    phone: '(31) 97654-3210',
    company: 'InovaLabs',
    role: 'Head de Produto',
    status: 'new',
    assigned_to: 'Luis Armando',
    created_at: '2026-06-05T14:00:00Z',
    updated_at: '2026-06-05T14:00:00Z',
  },
  {
    id: '4',
    workspace_id: 'ws-1',
    name: 'Carlos Eduardo Ferreira',
    email: 'carlos@grupoferre.com.br',
    phone: '(41) 98888-1234',
    company: 'Grupo Ferreira',
    role: 'Gerente Comercial',
    status: 'lost',
    assigned_to: 'Ana Costa',
    created_at: '2026-05-20T08:30:00Z',
    updated_at: '2026-06-10T16:45:00Z',
  },
  {
    id: '5',
    workspace_id: 'ws-1',
    name: 'Mariana Pires',
    email: 'mpires@construtoranova.com.br',
    phone: '(51) 99111-2233',
    company: 'Construtora Nova Era',
    role: 'Sócia-Fundadora',
    status: 'qualified',
    assigned_to: 'Luis Armando',
    created_at: '2026-06-08T11:20:00Z',
    updated_at: '2026-06-20T09:10:00Z',
  },
  {
    id: '6',
    workspace_id: 'ws-1',
    name: 'Paulo Henrique Lima',
    email: 'paulo@financeiroexpress.com',
    phone: '(11) 91234-5678',
    company: 'Financeiro Express',
    role: 'CFO',
    status: 'contacted',
    assigned_to: 'Pedro Alves',
    created_at: '2026-06-10T13:00:00Z',
    updated_at: '2026-06-19T10:30:00Z',
  },
  {
    id: '7',
    workspace_id: 'ws-1',
    name: 'Beatriz Almeida',
    email: 'beatriz@startupx.com.br',
    phone: '(21) 98765-0000',
    company: 'StartupX',
    role: 'Co-fundadora',
    status: 'new',
    assigned_to: 'Pedro Alves',
    created_at: '2026-06-12T15:45:00Z',
    updated_at: '2026-06-12T15:45:00Z',
  },
  {
    id: '8',
    workspace_id: 'ws-1',
    name: 'Thiago Rocha',
    email: 'thiago.rocha@varejo360.com.br',
    phone: '(61) 97777-8888',
    company: 'Varejo 360',
    role: 'Diretor de Operações',
    status: 'qualified',
    assigned_to: 'Ana Costa',
    created_at: '2026-06-14T08:00:00Z',
    updated_at: '2026-06-21T17:00:00Z',
  },
  {
    id: '9',
    workspace_id: 'ws-1',
    name: 'Camila Nascimento',
    email: 'camila@agenciacriar.com.br',
    phone: '(71) 99999-4321',
    company: 'Agência Criar',
    role: 'Diretora Criativa',
    status: 'contacted',
    assigned_to: 'Luis Armando',
    created_at: '2026-06-16T10:30:00Z',
    updated_at: '2026-06-22T14:00:00Z',
  },
  {
    id: '10',
    workspace_id: 'ws-1',
    name: 'Rafael Gomes',
    email: 'rafael@industrialgomes.ind.br',
    phone: '(11) 93456-7890',
    company: 'Industrial Gomes',
    role: 'Presidente',
    status: 'lost',
    assigned_to: 'Pedro Alves',
    created_at: '2026-05-28T09:00:00Z',
    updated_at: '2026-06-11T11:15:00Z',
  },
  {
    id: '11',
    workspace_id: 'ws-1',
    name: 'Amanda Texeira',
    email: 'amanda@saude360.com.br',
    phone: '(85) 98123-4567',
    company: 'Saúde 360',
    role: 'Gerente de TI',
    status: 'new',
    assigned_to: 'Ana Costa',
    created_at: '2026-06-20T16:00:00Z',
    updated_at: '2026-06-20T16:00:00Z',
  },
  {
    id: '12',
    workspace_id: 'ws-1',
    name: 'Lucas Monteiro',
    email: 'lucas@logisticaplus.com.br',
    phone: '(47) 97654-1234',
    company: 'Logística Plus',
    role: 'Gerente Comercial',
    status: 'qualified',
    assigned_to: 'Pedro Alves',
    created_at: '2026-06-18T12:00:00Z',
    updated_at: '2026-06-25T08:30:00Z',
  },
  {
    id: '13',
    workspace_id: 'ws-1',
    name: 'Isabela Fonseca',
    email: 'isa.fonseca@edutecbr.com.br',
    phone: '(11) 96543-2109',
    company: 'EduTec Brasil',
    role: 'Gerente de Parcerias',
    status: 'contacted',
    assigned_to: 'Ana Costa',
    created_at: '2026-06-22T09:00:00Z',
    updated_at: '2026-06-26T15:00:00Z',
  },
  {
    id: '14',
    workspace_id: 'ws-1',
    name: 'Rodrigo Cavalcante',
    email: 'rodrigo@ambienteplus.eco.br',
    phone: '(81) 98001-3344',
    company: 'Ambiente Plus',
    role: 'Diretor Executivo',
    status: 'new',
    assigned_to: 'Luis Armando',
    created_at: '2026-06-27T10:00:00Z',
    updated_at: '2026-06-27T10:00:00Z',
  },
  {
    id: '15',
    workspace_id: 'ws-1',
    name: 'Natália Vieira',
    email: 'natalia@mediahouse.com.br',
    phone: '(21) 97002-5566',
    company: 'Media House',
    role: 'Diretora de Vendas',
    status: 'lost',
    assigned_to: 'Pedro Alves',
    created_at: '2026-05-15T14:00:00Z',
    updated_at: '2026-06-05T09:00:00Z',
  },
]

export const MOCK_MEMBERS = ['Luis Armando', 'Ana Costa', 'Pedro Alves']

export const MOCK_ACTIVITIES = [
  // Fernanda Oliveira (lead 1)
  {
    id: 'a1',
    lead_id: '1',
    type: 'call' as const,
    description: 'Ligação inicial para apresentar o PipeFlow. Fernanda demonstrou interesse na plataforma e pediu uma proposta formal.',
    author: 'Luis Armando',
    date: '2026-06-15T14:30:00Z',
  },
  {
    id: 'a2',
    lead_id: '1',
    type: 'email' as const,
    description: 'Enviei a proposta comercial com preços e plano de implementação. Aguardando retorno até sexta.',
    author: 'Luis Armando',
    date: '2026-06-12T10:00:00Z',
  },
  {
    id: 'a3',
    lead_id: '1',
    type: 'meeting' as const,
    description: 'Reunião de discovery com o time de marketing. Mapeamos as dores principais: falta de visibilidade do funil e dificuldade de acompanhar leads.',
    author: 'Luis Armando',
    date: '2026-06-08T15:00:00Z',
  },
  {
    id: 'a4',
    lead_id: '1',
    type: 'note' as const,
    description: 'Lead veio por indicação da Mariana Pires. Alta probabilidade de fechamento — orçamento aprovado pela diretoria.',
    author: 'Luis Armando',
    date: '2026-06-01T10:00:00Z',
  },
  // Ricardo Mendes (lead 2)
  {
    id: 'a5',
    lead_id: '2',
    type: 'email' as const,
    description: 'Enviei e-mail de apresentação com deck institucional e cases de sucesso no segmento de tecnologia.',
    author: 'Ana Costa',
    date: '2026-06-18T11:00:00Z',
  },
  {
    id: 'a6',
    lead_id: '2',
    type: 'call' as const,
    description: 'Ricardo demonstrou interesse no plano Pro. Quer testar por 30 dias antes de fechar contrato anual.',
    author: 'Ana Costa',
    date: '2026-06-10T09:30:00Z',
  },
  {
    id: 'a7',
    lead_id: '2',
    type: 'note' as const,
    description: 'Empresa em expansão — prevê contratar 5 vendedores até agosto. Potencial de upgrade de plano a médio prazo.',
    author: 'Ana Costa',
    date: '2026-06-03T09:15:00Z',
  },
  // Mariana Pires (lead 5)
  {
    id: 'a8',
    lead_id: '5',
    type: 'meeting' as const,
    description: 'Apresentação do produto via videoconferência. Mariana adorou o Kanban e a visão de funil. Pediu acesso ao trial imediatamente.',
    author: 'Luis Armando',
    date: '2026-06-20T09:10:00Z',
  },
  {
    id: 'a9',
    lead_id: '5',
    type: 'call' as const,
    description: 'Follow-up pós-trial. Mariana relatou que a equipe já está usando diariamente. Pronta para assinar o plano anual.',
    author: 'Luis Armando',
    date: '2026-06-14T16:00:00Z',
  },
  {
    id: 'a10',
    lead_id: '5',
    type: 'note' as const,
    description: 'Prioridade alta. Decisão esperada até 30/06. Integrar com Thiago Rocha da Varejo 360 para benchmark.',
    author: 'Luis Armando',
    date: '2026-06-08T11:20:00Z',
  },
  // Paulo Henrique (lead 6)
  {
    id: 'a11',
    lead_id: '6',
    type: 'email' as const,
    description: 'Proposta customizada enviada com foco em relatórios financeiros e controle de comissões da equipe comercial.',
    author: 'Pedro Alves',
    date: '2026-06-19T10:30:00Z',
  },
  {
    id: 'a12',
    lead_id: '6',
    type: 'meeting' as const,
    description: 'Demo focada no módulo de relatórios e exportação para Excel. Paulo solicitou integração com o sistema contábil.',
    author: 'Pedro Alves',
    date: '2026-06-13T14:00:00Z',
  },
  // Thiago Rocha (lead 8)
  {
    id: 'a13',
    lead_id: '8',
    type: 'call' as const,
    description: 'Ligação de qualificação. Empresa tem 12 vendedores e usa planilha Excel. Forte potencial de migração para PipeFlow.',
    author: 'Ana Costa',
    date: '2026-06-21T17:00:00Z',
  },
  {
    id: 'a14',
    lead_id: '8',
    type: 'meeting' as const,
    description: 'Workshop com time de vendas para mapear processo atual. Identificamos 3 gargalos críticos que o PipeFlow resolve.',
    author: 'Ana Costa',
    date: '2026-06-17T10:00:00Z',
  },
  {
    id: 'a15',
    lead_id: '8',
    type: 'note' as const,
    description: 'Decisor é o Thiago, mas passa por aprovação do board. Próximo passo: apresentação executiva em 25/06.',
    author: 'Ana Costa',
    date: '2026-06-14T08:00:00Z',
  },
  // Camila Nascimento (lead 9)
  {
    id: 'a16',
    lead_id: '9',
    type: 'email' as const,
    description: 'Retorno ao contato após indicação de cliente. Camila respondeu em menos de 1h pedindo uma demo rápida.',
    author: 'Luis Armando',
    date: '2026-06-22T14:00:00Z',
  },
  {
    id: 'a17',
    lead_id: '9',
    type: 'call' as const,
    description: 'Call de 30 minutos para entender o processo atual. Agência tem 3 AEs e não usa CRM — oportunidade clara.',
    author: 'Luis Armando',
    date: '2026-06-16T10:30:00Z',
  },
  // Lucas Monteiro (lead 12)
  {
    id: 'a18',
    lead_id: '12',
    type: 'meeting' as const,
    description: 'Reunião de alinhamento com equipe de vendas da Logística Plus. Demonstramos integração com WhatsApp Business.',
    author: 'Pedro Alves',
    date: '2026-06-25T08:30:00Z',
  },
  {
    id: 'a19',
    lead_id: '12',
    type: 'email' as const,
    description: 'Proposta final enviada com desconto de 20% para plano semestral. Aguardando assinatura até 30/06.',
    author: 'Pedro Alves',
    date: '2026-06-20T11:00:00Z',
  },
]
